module.exports = {
  SUCCESS: 0,
  INVALID_LOCATION: 1,
  INVALID_USERID: 2,
  NO_ACCOUNTS_FOUND: 3,
  NOT_ENOUGH_URL_PARAMETERS: 4,
  TECHNICAL_ERROR: 5,
  INVALID_URL_PARAMETER: 6,
  NO_DRIVER_LICENSE: 7,
  ACCOUNT_LOCKED: 8,
  CANNOT_BOOK_CAR: 9,
  INVALID_VEHICLE: 10,
  INVALID_BOOKINGID: 11,
  NO_RESERVED_VEHICLE: 12
};
